---
# deploy_podman_stack.yml

- name: Deploy web stack with Podman (Nginx -> Flask -> MySQL)
  hosts: webserver
  gather_facts: true
  become: true
  vars:

    src_base_dir: "/home/webmaster/shipping-containers"          
    flask_ctx: "{{ src_base_dir }}"
    mysql_ctx: "{{ src_base_dir }}/mysql"
    nginx_ctx: "{{ src_base_dir }}/nginx"

    # Podman network & volumes
    podman_network: "shipping_containers_network"
    mysql_volume: "shipping_containers_data"

    # Systemd unit directory
    # systemd_unit_dir: "/etc/systemd/system"
    # Container extra run args (list)

  tasks:
  - name: Install Podman and its dependencies
    ansible.builtin.package:
      name:
        - podman
        - buildah
      state: present

  - name: Ensure app directory exists
    file:
      path: "{{ src_base_dir }}"
      state: directory
      owner: webmaster
      group: webmaster
      mode: "0755"

  - name: Create podman network
    containers.podman.podman_network:
        name: "{{ podman_network }}"
        state: present

  - name: Build mySQL image
    containers.podman.podman_image:
        name: mysql-image:1.0
        state: build
        path: "{{ mysql_ctx }}"
    

  - name: Run mySQL container
    containers.podman.podman_container:
        image: mysql-image:1.0
        name: mysql-container
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
        volumes:
          - "{{ mysql_volume }}:/var/lib/mysql"
        state: started
        network:
          - "{{ podman_network }}"
        detach: true
        restart_policy: always


  - name: Wait for MySQL port to be available
    wait_for:
      host: "127.0.0.1"
      port: 3306
      delay: 5
      timeout: 60

  - name: Create and start webserver pod
    containers.podman.podman_pod:
        name: webserver-pod
        state: started
        hostname: webserver-pod
        ports:
          - "80:80"
          - "5000:5000"
        network: 
          - "{{ podman_network }}"

  - name: Build Flask image
    containers.podman.podman_image:
        name: flask-app-image:1.0
        state: build
        path: "{{ flask_ctx }}"
        force: true
        build:
          cache: false
    

  - name: Run Flask container
    containers.podman.podman_container:
        image: flask-app-image:1.0
        name: flask-app-container
        env:
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
          DB_HOST: "mysql-container"
          DB_PORT: "3306"
        state: started
        detach: true
        restart_policy: always
        pod: webserver-pod

  - name: Build Nginx image
    containers.podman.podman_image:
        name: nginx-app-image:1.0
        state: build
        path: "{{ nginx_ctx }}"
        force: true
        build:
          cache: false
   
  - name: Run Nginx container
    containers.podman.podman_container:
        image: nginx-app-image:1.0
        name: nginx-app-container
        state: started
        detach: true
        restart_policy: always
        pod: webserver-pod

  - name: Prune dangling images
    containers.podman.podman_prune:
      image: true
   



 
  # - name: Pause briefly for containers to settle
  #   pause:
  #     seconds: 3

  # - name: Generate systemd unit for MySQL container
  #   command: podman generate systemd --new --name {{ mysql_ct }} --files --restart-policy=on-failure
  #   args:
  #     chdir: /tmp
  #   register: mysql_gen
  #   changed_when: "'Created' in mysql_gen.stdout or mysql_gen.rc == 0"

  # - name: Move mysql systemd unit into system folder
  #   shell: |
  #     mv /tmp/container-{{ mysql_ct }}.service {{ systemd_unit_dir }}/container-{{ mysql_ct }}.service
  #   args:
  #     warn: false
  #   when: "'/tmp/container-{{ mysql_ct }}.service' in lookup('fileglob','/tmp/*', errors='ignore') or (mysql_gen is defined and mysql_gen.stdout is search('container-'))"
  #   ignore_errors: yes

  # - name: Generate systemd unit for Flask container
  #   command: podman generate systemd --new --name {{ flask_ct }} --files --restart-policy=on-failure
  #   args:
  #     chdir: /tmp
  #   register: flask_gen
  #   changed_when: "'Created' in flask_gen.stdout or flask_gen.rc == 0"

  # - name: Move flask systemd unit into system folder
  #   shell: |
  #     mv /tmp/container-{{ flask_ct }}.service {{ systemd_unit_dir }}/container-{{ flask_ct }}.service
  #   args:
  #     warn: false
  #   ignore_errors: yes

  # - name: Generate systemd unit for Nginx container
  #   command: podman generate systemd --new --name {{ nginx_ct }} --files --restart-policy=on-failure
  #   args:
  #     chdir: /tmp
  #   register: nginx_gen
  #   changed_when: "'Created' in nginx_gen.stdout or nginx_gen.rc == 0"

  # - name: Move nginx systemd unit into system folder
  #   shell: |
  #     mv /tmp/container-{{ nginx_ct }}.service {{ systemd_unit_dir }}/container-{{ nginx_ct }}.service
  #   args:
  #     warn: false
  #   ignore_errors: yes

  # - name: Reload systemd daemon
  #   command: systemctl daemon-reload
  #   ignore_errors: false

  # - name: Enable and start mysql container service
  #   systemd:
  #     name: "container-{{ mysql_ct }}.service"
  #     enabled: true
  #     state: started
  #   ignore_errors: false

  # - name: Enable and start flask container service
  #   systemd:
  #     name: "container-{{ flask_ct }}.service"
  #     enabled: true
  #     state: started

  # - name: Enable and start nginx container service
  #   systemd:
  #     name: "container-{{ nginx_ct }}.service"
  #     enabled: true
  #     state: started

  - name: Show running podman containers
    command: podman ps --format json
    register: podman_ps
  - debug:
      var: podman_ps.stdout
