---
# deploy_podman_stack.yml

- name: Deploy web stack with Podman (Nginx -> Flask -> MySQL)
  hosts: webserver
  gather_facts: true
  become: false

  vars_files:
    - "vault"
  vars:

    runtime_dir: "/run/user/{{ ansible_user_uid }}"
    quadlet_dir: "/home/webmaster/.config/containers/systemd"

    src_base_dir: "/home/borysyy/shipping-containers"
    flask_ctx: "{{ src_base_dir }}"
    mysql_ctx: "{{ src_base_dir }}/mysql"
    nginx_ctx: "{{ src_base_dir }}/nginx"

    remote_flask_app_dir: "/home/webmaster/shipping-containers/"
    remote_mysql_app_dir: "/home/webmaster/shipping-containers/mysql"
    remote_nginx_app_dir: "/home/webmaster/shipping-containers/nginx"

    # Podman MySQL volume
    mysql_volume: "shipping_containers_data"

  tasks:
  - name: Install Podman and its dependencies
    ansible.builtin.package:
      name:
        - podman
        - buildah
      state: present
    become: true

  - name: Ensure all build contexts exist
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ remote_flask_app_dir }}"
      - "{{ remote_mysql_app_dir }}"
      - "{{ remote_nginx_app_dir }}"

  - name: Copy application files to remote host
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: webmaster
      group: webmaster
      mode: "0644"
    loop:
      - { src: "{{ flask_ctx }}/Containerfile", dest: "{{ remote_flask_app_dir }}/Containerfile" }
      - { src: "{{ flask_ctx }}/requirements.txt", dest: "{{ remote_flask_app_dir }}/requirements.txt" }
      - { src: "{{ flask_ctx }}/flask_project/", dest: "{{ remote_flask_app_dir }}/flask_project/" }
      - { src: "{{ mysql_ctx }}/", dest: "{{ remote_mysql_app_dir }}/" }
      - { src: "{{ nginx_ctx }}/", dest: "{{ remote_nginx_app_dir }}/" }
  
  - name: Copy nginx key to remote host
    copy:
      src: "{{ nginx_ctx }}/certs/project2.key"   
      dest: "{{ remote_nginx_app_dir }}/certs/project2.key"
      owner: webmaster
      group: webmaster
      mode: "0600"
    become: true

  - name: Ensure user systemd dir exists
    file:
      path: "{{ quadlet_dir }}"
      state: directory
      mode: "0755"
      owner: webmaster
      group: webmaster


  - name: Create webserver pod
    containers.podman.podman_pod:
        name: webserver
        state: quadlet
        hostname: webserver-pod
        quadlet_dir: "{{ quadlet_dir }}"
        ports:
          - "8443:443"

  - name: Build mySQL image
    containers.podman.podman_image:
        name: mysql-image:1.0
        state: build
        path: "{{ remote_mysql_app_dir }}"
    
  - name: Create mySQL container
    containers.podman.podman_container:
        image: mysql-image:1.0
        name: mysql-shipping_containers
        env:
          MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
          MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
          MYSQL_USER: "{{ MYSQL_USER }}"
          MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
        volumes:
          - "{{ mysql_volume }}:/var/lib/mysql"
        state: quadlet
        quadlet_dir: "{{ quadlet_dir }}"
        pod: webserver.pod

  - name: Build Flask image
    containers.podman.podman_image:
        name: flask-app-image:1.0
        state: build
        path: "{{ remote_flask_app_dir }}"
        force: true
        build:
          cache: false
  
  - name: Create Flask container
    containers.podman.podman_container:
        image: flask-app-image:1.0
        name: flask-app-shipping_containers
        env:
          MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
          MYSQL_USER: "{{ MYSQL_USER }}"
          MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
          DB_HOST: "localhost"
          DB_PORT: "3306"
        state: quadlet
        quadlet_dir: "{{ quadlet_dir }}"
        pod: webserver.pod

  - name: Build Nginx image
    containers.podman.podman_image:
        name: nginx-app-image:1.0
        state: build
        path: "{{ remote_nginx_app_dir}}/configs"
        force: true
        build:
          cache: false
   
  - name: Create Nginx container
    containers.podman.podman_container:
        image: nginx-app-image:1.0
        name: nginx-app-shipping_containers
        state: quadlet
        quadlet_dir: "{{ quadlet_dir }}"
        pod: webserver.pod
        volumes:
          - "{{ remote_nginx_app_dir }}/certs:/etc/nginx/certs:ro"

      
  - name: Reload user systemd
    ansible.builtin.systemd_service:
      daemon_reload: true
      scope: user
    environment:
      XDG_RUNTIME_DIR: "{{ runtime_dir }}"

  - name: Start webserver pod
    ansible.builtin.systemd_service:
      name: webserver-pod.service
      state: started
      enabled: true
      scope: user
    environment:
      XDG_RUNTIME_DIR: "{{ runtime_dir }}"

  - name: Prune dangling images
    containers.podman.podman_prune:
      image: true
   